# Generated by Django 6.0.3 on 2026-04-11 10:30

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_hero_cta_homepage_hero_cta_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_posts',
            field=wagtail.fields.StreamField([('post', 0)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['blog.BlogPage']})}, help_text='Pivck blog posts to feature on the homepage.'),
        ),
    ]
