# Generated by Django 6.0.3 on 2026-04-11 11:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_featured_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_projects',
            field=wagtail.fields.StreamField([('project', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Python, JS, Django, etc...'}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'Link to the GitHub repo'}), 4: ('wagtail.blocks.URLBlock', (), {'help_text': 'Live link, if available', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('tech_stack', 2), ('repo_link', 3), ('deployed_link', 4)]], {})}, help_text='Use this section to showcase your projects'),
        ),
    ]
