# Generated by Django 6.0.3 on 2026-04-14 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_featured_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='body',
            new_name='intro',
        ),
    ]
