# Generated by Django 6.0.3 on 2026-04-14 11:16

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_body_homepage_intro'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='top_project_image',
            field=models.ForeignKey(blank=True, help_text='Top project image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='top_project_stack',
            field=models.TextField(blank=True, help_text='One technology per line, for example: Python then Django then PostgreSQL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='top_project_text',
            field=models.TextField(blank=True, help_text='Short project description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='top_project_title',
            field=models.CharField(blank=True, help_text='Main title for the top project card', max_length=120),
        ),
    ]
