# Generated by Django 6.0.3 on 2026-04-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_about_homepage_top_project_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='top_project_dep',
            field=models.URLField(blank=True, help_text='Link to the deployed site'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='top_project_gh',
            field=models.URLField(blank=True, help_text='Link to the GitHub repo'),
        ),
    ]
