# Generated by Django 6.0.3 on 2026-04-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_top_project_dep_homepage_top_project_gh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='top_project_dep',
            field=models.URLField(blank=True, verbose_name='Link to the deployed site'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='top_project_gh',
            field=models.URLField(blank=True, verbose_name='Link to the GitHub repo'),
        ),
    ]
