# Generated by Django 6.0.3 on 2026-04-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_homepage_top_project_dep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_lead',
            field=models.CharField(blank=True, help_text='Write an introduction for the site', max_length=255),
        ),
    ]
