# Generated by Django 6.0.3 on 2026-04-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_formpage_formfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationsettings',
            name='mastodon_url',
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Your work Email'),
        ),
    ]
