# Generated by Django 6.0.3 on 2026-04-16 12:08

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogtagindexpage_blogpagetag_blogpage_tags'),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE blog_blogpage SET body = '[]' WHERE body IS NOT NULL AND body != '[]';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('code_block', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'link', 'image', 'code', 'colour-red'], 'label': 'Rich Text'}), 1: ('wagtail.blocks.ChoiceBlock', [], {
                                             'choices': [('python', 'Python'), ('javascript', 'JavaScript'), ('bash', 'Bash'), ('html', 'HTML'), ('css', 'CSS'), ('json', 'JSON'), ('sql', 'SQL')]}), 2: ('wagtail.blocks.TextBlock', (), {'required': True}), 3: ('wagtail.blocks.StructBlock', [[('language', 1), ('code', 2)]], {})}),
        ),
    ]
